project:
  type: book
  output-dir: "book"

book:
  title: "Snowball Stemming Manual"
  author:
    - name: Dr. Martin Porter
    - name: Richard Boulton
  date: today
  date-format: "YYYY"
  chapters:
    - index.qmd
    - part: "Overviews"
      chapters:
      - overviews\r1r2.qmd
      - overviews\vowelmarking.qmd
      - overviews\apostrophe.qmd
    - part: "Algorithms"
      chapters:
      - danish.qmd
      - dutch_porter.qmd
      - english.qmd
      - finnish.qmd
      - french.qmd
      - german.qmd
      - italian.qmd
      - norwegian.qmd
      - portuguese.qmd
      - russian.qmd
      - spanish.qmd
      - swedish.qmd
    - part: "Index"
      chapters:
      - glossary.qmd
      - license.qmd
      - credits.qmd
      - references.qmd

format:
  pdf:
    documentclass: report
    pdf-engine: xelatex
    header-includes:
      - \usepackage[Lenny]{fncychap}
      - \usepackage{fontspec}
      - \usepackage{noto}
      - \usepackage[letterpaper, margin=1in]{geometry}
