project:
  type: book
  output-dir: "book"

biblio-title: References
bibliography: cites.bib
biblio-style: mla

book:
  title: "Stemming Manual"
  author:
    - name: Dr. Martin Porter
    - name: Richard Boulton
  date: today
  date-format: "YYYY"
  chapters:
    - index.qmd
    - part: "Algorithms"
      chapters:
    - english.qmd
      - danish.qmd
      - finnish.qmd
      - german.qmd
    - part: "Index"
      chapters:
      - glossary.qmd
      - r1r2.qmd
      - vowelmarking.qmd
      - apostrophe.qmd

format:
  pdf:
    documentclass: scrreprt
    citation-package: biblatex
    cite-method: biblatex
