# Glossary

## _a_\-suffix {-}

An _a_\-suffix, or _attached_ suffix, is a particle word attached to another word. (In the stemming literature they sometimes get referred to as ‘enclitics’.) In Italian, for example, personal pronouns attach to certain verb forms:

|     |     |     |     |     |     |     |
| --- | --- | --- | --- | --- | --- | --- |
| mandargli = |     | mandare + **_gli_** |     | \=  |     | to send + to him |
| mandarglielo = |     | mandare + **_gli_** + **_lo_** |     | \=  |     | to send + it + to him |

_a_\-suffixes appear in Italian and Spanish, and also in Portuguese, although in Portuguese they are separated by hyphen from the preceding word, which makes them easy to eliminate.

## _i_\-suffix {-}

An _i_\-suffix, or _inflectional_ suffix, forms part of the basic grammar of a language, and is applicable to all words of a certain grammatical type, with perhaps a small number of exceptions. In English for example, the past of a verb is formed by adding **_ed_**. Certain modifications may be required in the stem:

|     |     |     |     |     |
| --- | --- | --- | --- | --- |
| fit + **_ed_** |     | →   |     | fitted (double **_t_**) |
| love + **_ed_** |     | →   |     | loved (drop the final **_e_** of love) |

## _d_\-suffix {-}

A _d_\-suffix, or _derivational_ suffix, enables a new word, often with a different grammatical category, or with a different sense, to be built from another word. Whether a _d_\-suffix can be attached is discovered not from the rules of grammar, but by referring to a dictionary. So in English, **_ness_** can be added to certain adjectives to form corresponding nouns (_littleness_, _kindness_, _foolishness_ ...) but not to all adjectives (not for example, to _big_, _cruel_, _wise_ ...) _d_\-suffixes can be used to change meaning, often in rather exotic ways. So in italian **_astro_** means a sham form of something else:

|     |     |     |     |     |     |     |     |     |
| --- | --- | --- | --- | --- | --- | --- | --- | --- |
| medico + **_astro_** |     | \=  |     | medicastro |     | \=  |     | quack doctor |
| poeta + **_astro_** |     | \=  |     | poetastro |     | \=  |     | poetaster |

## Indo-European languages {-}

Most European and many Asian languages belong to the Indo-European language group. Historically, it includes the Latin, Greek, Persian and Sanskrit of the ancient world, and with the rise of the European empires, languages of this group are now dominant in the Americas, Australia and large parts of Africa. Indo-European languages are therefore the main languages of modern Western culture, and they are all similarly amenable to stemming.

The Indo-European group has many recognisable sub-groups, for example _Romance_ (Italian, French, Spanish ...), _Slavonic_ (Russian, Polish, Czech ...), _Celtic_ (Irish Gaelic, Scottish Gaelic, Welsh ...). The _Germanic_ sub-group includes German and Dutch, and the _Scandinavian_ languages are also usually classed as Germanic, although for convenience we have made a separate grouping of them on the Snowball site. English is also classed as Germanic, although it has been classed separately by us. This is not for reasons of narrow chauvinism, but because the suffix structure of English clearly lies mid-way between the Germanic and Romance groups, and it therefore requires separate treatment.

## Uralic languages {-}

The Uralic languages are spoken mainly in Northern Russia and Europe. They are divided into Samoyed, spoken mainly in the Siberian region, and Finno-Ugric, spoken mainly in Europe. Although the number of languages in the group is substantial, the total number of speakers is relatively small. The best known Uralic languages are perhaps Hungarian, Finnish and Estonian. Finnish and Estonian are in fact fairly similar. On the other hand Hungarian and Finnish are as different as are, say, French and Persian in the Indo-European group.

Like the Indo-European languages, the Uralic languages are amenable to stemming.