# Spanish stemming algorithm {#sec-spanish}

## Design Notes

Accents are often missing in informally written Spanish. Since Snowball 3.0.0 some additional rules are included to try to handle commonly occurring cases where accents are omitted and an additional rule doesn't cause problems with other words. There's likely scope for further such improvements - please report instances.

## History of functional changes to the algorithm

*   2005-06-15: Added rules to remove _\-ante_, _\-antes_, _\-ancia_ and _\-ancias_
*   Snowball 3.0.0: Added rules to remove _\-acion_ and _\-ucion_.

## The stemming algorithm

Letters in Spanish include the following accented forms,

&ensp;&ensp;**_á &nbsp; é &nbsp; í &nbsp; ó &nbsp; ú &nbsp; ü &nbsp; ñ_**

The following letters are vowels:

&ensp;&ensp;**_a &nbsp; e &nbsp; i &nbsp; o &nbsp; u &nbsp; á &nbsp; é &nbsp; í &nbsp; ó &nbsp; ú &nbsp; ü_**

_R2_ is defined in the usual way — see the [note](#sec-r1r2) on _R1_ and _R2_.

_RV_ is defined as follows (and this is not the same as the [French stemmer](#sec-french) definition):

If the second letter is a consonant, _RV_ is the region after the next following vowel, or if the first two letters are vowels, _RV_ is the region after the next consonant, and otherwise (consonant-vowel case) _RV_ is the region after the third letter. But _RV_ is the end of the word if these positions cannot be found.

For example,

    m a c h o     o l i v a     t r a b a j o     á u r e o
         |...|         |...|         |.......|         |...|

Always do steps 0 and 1.

Step 0: Attached pronoun

Search for the longest among the following suffixes

&ensp;&ensp;**_me &nbsp; se &nbsp; sela &nbsp; selo &nbsp; selas &nbsp; selos &nbsp; la &nbsp; le &nbsp; lo &nbsp; las &nbsp; les &nbsp; los &nbsp; nos_**

and delete it, if comes after one of

&ensp;&ensp;(_a_) **_iéndo &nbsp; ándo &nbsp; ár &nbsp; ér &nbsp; ír_**  
&ensp;&ensp;(_b_) **_ando &nbsp; iendo &nbsp; ar &nbsp; er &nbsp; ir_**  
&ensp;&ensp;(_c_) **_yendo_** following **_u_**

in _RV_. In the case of (_c_), **_yendo_** must lie in _RV_, but the preceding **_u_** can be outside it.

In the case of (_a_), deletion is followed by removing the acute accent (for example, _haciéndola_ » _haciendo_).

Step 1: Standard suffix removal

&ensp;&ensp;Search for the longest among the following suffixes, and perform the action indicated.

&ensp;&ensp;&ensp;&ensp;**_anza &nbsp; anzas &nbsp; ico &nbsp; ica &nbsp; icos &nbsp; icas &nbsp; ismo &nbsp; ismos &nbsp; able &nbsp; ables &nbsp; ible &nbsp; ibles &nbsp; ista &nbsp; istas &nbsp; oso &nbsp; osa &nbsp; osos &nbsp; osas &nbsp; amiento &nbsp; amientos &nbsp; imiento &nbsp; imientos_**

&ensp;&ensp;&ensp;&ensp;&ensp;&ensp;delete if in _R2_

&ensp;&ensp;&ensp;&ensp;**_adora &nbsp; ador &nbsp; ación &nbsp; adoras &nbsp; adores &nbsp; aciones &nbsp; ante &nbsp; antes &nbsp; ancia &nbsp; ancias &nbsp; acion_**

&ensp;&ensp;&ensp;&ensp;&ensp;&ensp;delete if in _R2_

&ensp;&ensp;&ensp;&ensp;&ensp;&ensp;if preceded by **_ic_**, delete if in _R2_

&ensp;&ensp;&ensp;&ensp;**_logía &nbsp; logías_**

&ensp;&ensp;&ensp;&ensp;&ensp;&ensp;replace with **_log_** if in _R2_

&ensp;&ensp;&ensp;&ensp;**_ución &nbsp; uciones &nbsp; ucion_**

&ensp;&ensp;&ensp;&ensp;&ensp;&ensp;replace with **_u_** if in _R2_

&ensp;&ensp;&ensp;&ensp;**_encia &nbsp; encias_**

&ensp;&ensp;&ensp;&ensp;&ensp;&ensp;replace with **_ente_** if in _R2_

&ensp;&ensp;&ensp;&ensp;**_amente_**

&ensp;&ensp;&ensp;&ensp;&ensp;&ensp;delete if in _R1_

&ensp;&ensp;&ensp;&ensp;&ensp;&ensp;if preceded by **_iv_**, delete if in _R2_ (and if further preceded by **_at_**, delete if in _R2_), otherwise,

&ensp;&ensp;&ensp;&ensp;&ensp;&ensp;if preceded by **_os_**, **_ic_** or **_ad_**, delete if in _R2_

&ensp;&ensp;&ensp;&ensp;**_mente_**

&ensp;&ensp;&ensp;&ensp;&ensp;&ensp;delete if in _R2_

&ensp;&ensp;&ensp;&ensp;&ensp;&ensp;if preceded by **_ante_**, **_able_** or **_ible_**, delete if in _R2_

&ensp;&ensp;&ensp;&ensp;**_idad &nbsp; idades_**

&ensp;&ensp;&ensp;&ensp;&ensp;&ensp;delete if in _R2_

&ensp;&ensp;&ensp;&ensp;&ensp;&ensp;if preceded by **_abil_**, **_ic_** or **_iv_**, delete if in _R2_

&ensp;&ensp;&ensp;&ensp;**_iva &nbsp; ivo &nbsp; ivas &nbsp; ivos_**

&ensp;&ensp;&ensp;&ensp;&ensp;&ensp;delete if in _R2_

&ensp;&ensp;&ensp;&ensp;&ensp;&ensp;if preceded by **_at_**, delete if in _R2_

Do step _2a_ if no ending was removed by step 1.

Step _2a_: Verb suffixes beginning **_y_**

&ensp;&ensp;Search for the longest among the following suffixes in _RV_, and if found, delete if preceded by **_u_**.

&ensp;&ensp;&ensp;&ensp;**_ya &nbsp; ye &nbsp; yan &nbsp; yen &nbsp; yeron &nbsp; yendo &nbsp; yo &nbsp; yó &nbsp; yas &nbsp; yes &nbsp; yais &nbsp; yamos_**

&ensp;&ensp;(Note that the preceding u need not be in _RV_.)

Do Step _2b_ if step _2a_ was done, but failed to remove a suffix.

Step _2b_: Other verb suffixes

&ensp;&ensp;Search for the longest among the following suffixes in _RV_, and perform the action indicated.

&ensp;&ensp;&ensp;&ensp;**_en &nbsp; es &nbsp; éis &nbsp; emos_**

&ensp;&ensp;&ensp;&ensp;&ensp;&ensp;delete, and if preceded by **_gu_** delete the **_u_** (the **_gu_** need not be in _RV_)

&ensp;&ensp;&ensp;&ensp;**_arían &nbsp; arías &nbsp; arán &nbsp; arás &nbsp; aríais &nbsp; aría &nbsp; aréis &nbsp; aríamos &nbsp; aremos &nbsp; ará &nbsp; aré &nbsp; erían &nbsp; erías &nbsp; erán &nbsp; erás &nbsp; eríais &nbsp; ería &nbsp; eréis &nbsp; eríamos &nbsp; eremos &nbsp; erá &nbsp; eré &nbsp; irían &nbsp; irías &nbsp; irán &nbsp; irás &nbsp; iríais &nbsp; iría &nbsp; iréis &nbsp; iríamos &nbsp; iremos &nbsp; irá &nbsp; iré &nbsp; aba &nbsp; ada &nbsp; ida &nbsp; ía &nbsp; ara &nbsp; iera &nbsp; ad &nbsp; ed &nbsp; id &nbsp; ase &nbsp; iese &nbsp; aste &nbsp; iste &nbsp; an &nbsp; aban &nbsp; ían &nbsp; aran &nbsp; ieran &nbsp; asen &nbsp; iesen &nbsp; aron &nbsp; ieron &nbsp; ado &nbsp; ido &nbsp; ando &nbsp; iendo &nbsp; ió &nbsp; ar &nbsp; er &nbsp; ir &nbsp; as &nbsp; abas &nbsp; adas &nbsp; idas &nbsp; ías &nbsp; aras &nbsp; ieras &nbsp; ases &nbsp; ieses &nbsp; ís &nbsp; áis &nbsp; abais &nbsp; íais &nbsp; arais &nbsp; ierais &nbsp; &nbsp; aseis &nbsp; ieseis &nbsp; asteis &nbsp; isteis &nbsp; ados &nbsp; idos &nbsp; amos &nbsp; ábamos &nbsp; íamos &nbsp; imos &nbsp; áramos &nbsp; iéramos &nbsp; iésemos &nbsp; ásemos_**

&ensp;&ensp;&ensp;&ensp;&ensp;&ensp;delete

Always do step 3.

Step 3: residual suffix

&ensp;&ensp;Search for the longest among the following suffixes in _RV_, and perform the action indicated.

&ensp;&ensp;&ensp;&ensp;**_os &nbsp; a &nbsp; o &nbsp; á &nbsp; í &nbsp; ó_**

&ensp;&ensp;&ensp;&ensp;&ensp;&ensp;delete if in _RV_

&ensp;&ensp;&ensp;&ensp;**_e &nbsp; é_**

&ensp;&ensp;&ensp;&ensp;&ensp;&ensp;delete if in _RV_, and if preceded by **_gu_** with the **_u_** in _RV_ delete the **_u_**

And finally:

&ensp;&ensp;Remove acute accents