name: doxygen
on: [push]

jobs:
  build:
    name: doxygen-test
    runs-on: ubuntu-latest
    permissions:
      contents: read
    steps:
      - uses: actions/checkout@v4
        with:
          submodules: 'true'

      - name: install doxygen
        run: |
             sudo apt install doxygen

      - name: run doxygen
        run: |
             cd docs
             doxygen Doxyfile
