name: quneiform
on: [push]

jobs:
  build:
    name: quneiform
    runs-on: ubuntu-latest
    permissions:
      contents: read
    steps:
      - uses: actions/checkout@v4

      - name: install quneiform
        run: |
             git clone https://github.com/eclipse-quneiform/quneiform.git --recurse-submodules
             cd quneiform
             cmake ./
             make -j4
             cd ..

      - name: analyze
        run: |
             # Ignore quneiform's own folder.
             # You can ignore other folders by adding a comma and the folder name
             # after "--ignore=quneiform".
             ./quneiform/bin/quneiform ./src -q --enable=allCodeFormatting -o i18nresults.txt

      - name: review results
        run: |
             REPORTFILE=./i18nresults.txt
             WARNINGSFILE=./warnings.txt
             if test -f "$REPORTFILE"; then
                cat "$REPORTFILE" > "$WARNINGSFILE"
                # are there any warnings?
                if grep -qP '\[[a-zA-Z0-9]+\]' "$WARNINGSFILE"; then
                    # print the remaining warnings
                    echo Warnings detected:
                    echo ==================
                    cat "$WARNINGSFILE" | grep -P '\[[a-zA-Z0-9]+\]'
                    # fail the job
                    exit 1
                else
                    echo No issues detected
                fi
             else
                echo "$REPORTFILE" not found
             fi
